# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "be568a9cffdc96ed84b3e81858a85893"
name = "atahome-design"
handle = "atahome-design-1"
application_url = "https://cad-merry-wrap-messenger.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-b348cff7.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://cad-merry-wrap-messenger.trycloudflare.com/auth/callback",
  "https://cad-merry-wrap-messenger.trycloudflare.com/auth/shopify/callback",
  "https://cad-merry-wrap-messenger.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
